// Generated by tools/style_catalog/add_style_schemes.py. Do not edit manually.

import Foundation

enum AestheticGeneratedCatalog {
    static let styles: [AestheticBuildStyle] = [
        style(
            id: "unknownPlayerP80Mesh",
            title: "未知玩家P80 MESH",
            summary: "网孔机箱与双塔风冷、六把灯效风扇组成的黑白展示方案",
            image: "StyleUnknownPlayerP80MeshBlack",
            tags: ["网孔机箱", "六把风扇"],
            signature: "保留未知玩家 P80 MESH 机箱和基础风扇布局",
            highDetail: "保留超频三 RZ620M X 风冷与六把棱镜 8 Pro 风扇",
            completeDetail: "完整保留 P80 MESH、RZ620M X 风冷和六把棱镜 8 Pro 风扇",
            costs: [AestheticPriceRange(low: 577, high: 577), AestheticPriceRange(low: 577, high: 577), AestheticPriceRange(low: 577, high: 577)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "colorfulC25A",
            title: "七彩虹 C25A",
            summary: "紧凑海景房机箱与360水冷、四把灯效风扇组成的展示方案",
            image: "StyleColorfulC25ABlack",
            tags: ["紧凑海景房", "四把风扇"],
            signature: "保留七彩虹 C25A 机箱和基础风扇布局",
            highDetail: "保留利民 PV360 水冷与四把棱镜 8 Pro 风扇",
            completeDetail: "完整保留 C25A、PV360 水冷和四把棱镜 8 Pro 风扇",
            costs: [AestheticPriceRange(low: 1138, high: 1138), AestheticPriceRange(low: 1138, high: 1138), AestheticPriceRange(low: 1138, high: 1138)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "xingcanChenScreen",
            title: "爱国者星璨辰 屏显版",
            summary: "屏显机箱与魔方风扇、360水冷组成的高辨识度海景房方案",
            image: "StyleXingcanChenScreenBlack",
            tags: ["屏显海景房", "魔方风扇"],
            signature: "保留爱国者星璨辰屏显版机箱和基础风扇布局",
            highDetail: "保留利民 MV360 水冷与魔方风扇组合",
            completeDetail: "完整保留星璨辰屏显版、MV360 水冷和三把 U360、一把 U120 风扇",
            costs: [AestheticPriceRange(low: 1864, high: 1864), AestheticPriceRange(low: 1864, high: 1864), AestheticPriceRange(low: 1864, high: 1864)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "wanjiaWenjieMin",
            title: "玩嘉问界MIN",
            summary: "开放式海景房机箱与双塔风冷、五把灯效风扇组成的展示方案",
            image: "StyleWanjiaWenjieMinBlack",
            tags: ["开放式海景房", "五把风扇"],
            signature: "保留玩嘉问界 MIN 机箱和基础风扇布局",
            highDetail: "保留瓦尔基里 DQ125 双塔风冷与五把棱镜 8 Pro 风扇",
            completeDetail: "完整保留问界 MIN、DQ125 双塔风冷和五把棱镜 8 Pro 风扇",
            costs: [AestheticPriceRange(low: 398, high: 398), AestheticPriceRange(low: 398, high: 398), AestheticPriceRange(low: 398, high: 398)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "wanjiaDreamerScreen",
            title: "玩嘉 梦想家副屏版",
            summary: "副屏机箱与360水冷、六把灯效风扇组成的高辨识度展示方案",
            image: "StyleWanjiaDreamerScreenBlack",
            tags: ["副屏海景房", "六把风扇"],
            signature: "保留玩嘉梦想家副屏版机箱和基础风扇布局",
            highDetail: "保留九州风神冰元素 360 ARGB 水冷与六把棱镜 8 Pro 风扇",
            completeDetail: "完整保留梦想家副屏版、冰元素 360 ARGB 水冷和六把棱镜 8 Pro 风扇",
            costs: [AestheticPriceRange(low: 697, high: 697), AestheticPriceRange(low: 697, high: 697), AestheticPriceRange(low: 697, high: 697)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "phanteksXTV3Breeze",
            title: "追风者 XT V3 小清风",
            summary: "紧凑网孔机箱与360水冷、四把灯效风扇组成的清爽展示方案",
            image: "StylePhanteksXTV3BreezeBlack",
            tags: ["紧凑机箱", "四把风扇"],
            signature: "保留追风者 XT V3 小清风机箱和基础风扇布局",
            highDetail: "保留利民 AE360 水冷与四把棱镜 8 Pro 风扇",
            completeDetail: "完整保留 XT V3 小清风、AE360 水冷和四把棱镜 8 Pro 风扇",
            costs: [AestheticPriceRange(low: 588, high: 588), AestheticPriceRange(low: 588, high: 588), AestheticPriceRange(low: 588, high: 588)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "hangjiaG63Waraxe",
            title: "航嘉 G63 战戟",
            summary: "前置网孔机箱与360水冷、九把灯效风扇组成的高性价比展示方案",
            image: "StyleHangjiaG63WaraxeBlack",
            tags: ["前置网孔", "九把风扇"],
            signature: "保留航嘉 G63 战戟机箱和基础风扇布局",
            highDetail: "保留利民 AE360 水冷与九把棱镜 4 Pro 风扇",
            completeDetail: "完整保留 G63 战戟、AE360 水冷和九把棱镜 4 Pro 风扇",
            costs: [AestheticPriceRange(low: 557, high: 557), AestheticPriceRange(low: 557, high: 557), AestheticPriceRange(low: 557, high: 557)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        ),
        style(
            id: "valkyrieVK03M",
            title: "瓦尔基里 VK03-M",
            summary: "瓦尔基里 VK03-M 机箱与 B360-GT 水冷、九把灯效风扇组成的黑白展示方案",
            image: "StyleValkyrieVK03MBlack",
            tags: ["海景房机箱", "九把风扇"],
            signature: "保留瓦尔基里 VK03-M 机箱和基础风扇布局",
            highDetail: "保留瓦尔基里 B360-GT 水冷与九把棱镜 8 Pro 风扇",
            completeDetail: "完整保留 VK03-M、B360-GT 水冷和九把棱镜 8 Pro 风扇",
            costs: [AestheticPriceRange(low: 917, high: 917), AestheticPriceRange(low: 917, high: 917), AestheticPriceRange(low: 917, high: 917)],
            premiums: [AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0), AestheticPriceRange(low: 0, high: 0)]
        )
    ]

    private static let imageNames: [String: (black: String, white: String)] = [
        "unknownPlayerP80Mesh": (black: "StyleUnknownPlayerP80MeshBlack", white: "StyleUnknownPlayerP80MeshWhite"),
        "colorfulC25A": (black: "StyleColorfulC25ABlack", white: "StyleColorfulC25AWhite"),
        "xingcanChenScreen": (black: "StyleXingcanChenScreenBlack", white: "StyleXingcanChenScreenWhite"),
        "wanjiaWenjieMin": (black: "StyleWanjiaWenjieMinBlack", white: "StyleWanjiaWenjieMinWhite"),
        "wanjiaDreamerScreen": (black: "StyleWanjiaDreamerScreenBlack", white: "StyleWanjiaDreamerScreenWhite"),
        "phanteksXTV3Breeze": (black: "StylePhanteksXTV3BreezeBlack", white: "StylePhanteksXTV3BreezeWhite"),
        "hangjiaG63Waraxe": (black: "StyleHangjiaG63WaraxeBlack", white: "StyleHangjiaG63WaraxeWhite"),
        "valkyrieVK03M": (black: "StyleValkyrieVK03MBlack", white: "StyleValkyrieVK03MWhite")
    ]

    private static let partsByStyleID: [String: [AestheticStylePart]] = [
        "unknownPlayerP80Mesh": [
        part("unknownplayerp80mesh", "机箱", "未知玩家 P80 MESH", 299, []),
        part("unknownplayerp80mesh", "散热器", "超频三 RZ620M X 风冷", 219, []),
        part("unknownplayerp80mesh", "风扇套装", "棱镜 8 Pro × 6", 59, [])
        ],
        "colorfulC25A": [
        part("colorfulc25a", "机箱", "七彩虹 C25A", 599, []),
        part("colorfulc25a", "一体式水冷", "利民 PV360", 499, []),
        part("colorfulc25a", "风扇套装", "棱镜 8 Pro × 4", 40, [])
        ],
        "xingcanChenScreen": [
        part("xingcanchenscreen", "机箱", "爱国者星璨辰 屏显版", 699, []),
        part("xingcanchenscreen", "风扇套装", "魔方 U360 × 3 + 魔方 U120 × 1", 566, []),
        part("xingcanchenscreen", "一体式水冷", "利民 MV360", 599, [])
        ],
        "wanjiaWenjieMin": [
        part("wanjiawenjiemin", "机箱", "玩嘉问界 MIN", 209, []),
        part("wanjiawenjiemin", "风冷散热器", "瓦尔基里 DQ125 双塔 6 热管风冷", 139, []),
        part("wanjiawenjiemin", "风扇套装", "棱镜 8 Pro × 5", 50, [])
        ],
        "wanjiaDreamerScreen": [
        part("wanjiadreamerscreen", "机箱", "玩嘉 梦想家副屏版", 339, []),
        part("wanjiadreamerscreen", "一体式水冷", "九州风神 冰元素 360 ARGB 水冷", 299, []),
        part("wanjiadreamerscreen", "风扇套装", "棱镜 8 Pro × 6", 59, [])
        ],
        "phanteksXTV3Breeze": [
        part("phanteksxtv3breeze", "机箱", "追风者 XT V3 小清风", 249, []),
        part("phanteksxtv3breeze", "风扇套装", "棱镜 8 Pro × 4", 40, []),
        part("phanteksxtv3breeze", "一体式水冷", "利民 AE360", 299, [])
        ],
        "hangjiaG63Waraxe": [
        part("hangjiag63waraxe", "机箱", "航嘉 G63 战戟", 169, []),
        part("hangjiag63waraxe", "风扇套装", "棱镜 4 Pro × 9", 89, []),
        part("hangjiag63waraxe", "一体式水冷", "利民 AE360", 299, [])
        ],
        "valkyrieVK03M": [
        part("valkyrievk03m", "机箱", "瓦尔基里 VK03-M", 329, []),
        part("valkyrievk03m", "一体式水冷", "瓦尔基里 B360-GT", 499, []),
        part("valkyrievk03m", "风扇套装", "棱镜 8 Pro × 9", 89, [])
        ]
    ]

    static func image(for styleID: String, color: AestheticStyleColor) -> String? {
        guard let names = imageNames[styleID] else { return nil }
        return color == .black ? names.black : names.white
    }

    static func parts(for styleID: String) -> [AestheticStylePart]? {
        partsByStyleID[styleID]
    }

    private static func style(
        id: String,
        title: String,
        summary: String,
        image: String,
        tags: [String],
        signature: String,
        highDetail: String,
        completeDetail: String,
        costs: [AestheticPriceRange],
        premiums: [AestheticPriceRange]
    ) -> AestheticBuildStyle {
        AestheticBuildStyle(
            id: id,
            title: title,
            summary: summary,
            image: image,
            tags: tags,
            options: [
                AestheticRestorationOption(tier: .core, fidelity: 65, styleCost: costs[0], premium: premiums[0], keeps: signature, tradeoff: "使用基础散热和必要风扇"),
                AestheticRestorationOption(tier: .high, fidelity: 85, styleCost: costs[1], premium: premiums[1], keeps: highDetail, tradeoff: "不补满装饰风扇"),
                AestheticRestorationOption(tier: .complete, fidelity: 95, styleCost: costs[2], premium: premiums[2], keeps: completeDetail, tradeoff: "保留同风格型号替代空间")
            ]
        )
    }

    private static func part(
        _ prefix: String,
        _ name: String,
        _ detail: String,
        _ price: Int,
        _ alternatives: [AestheticStyleAlternative]
    ) -> AestheticStylePart {
        AestheticStylePart(
            id: "\(prefix)-\(name)",
            name: name,
            detail: detail,
            price: price,
            whitePrice: nil,
            alternatives: alternatives
        )
    }

    private static func alternative(_ name: String, _ price: Int, _ detail: String) -> AestheticStyleAlternative {
        AestheticStyleAlternative(id: name, name: name, price: price, whitePrice: nil, detail: detail)
    }
}
